
services:
  oracle-xe:
    image: gvenzl/oracle-xe
    platform: linux/amd64   # ✅ needed on Apple Silicon
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: hr_app
      APP_USER_PASSWORD: hr_password
    ports:
      - "1521:1521"
      - "5500:5500"

  backend:
    build: ../backend
    container_name: backend
    depends_on:
      - oracle-xe
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"

  frontend:
    build: ../frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"