CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID VARCHAR2(32) PRIMARY KEY,
  FIRST_NAME  VARCHAR2(100) NOT NULL,
  LAST_NAME   VARCHAR2(100) NOT NULL,
  DIVISION    VARCHAR2(100),
  BUILDING    VARCHAR2(100),
  TITLE       VARCHAR2(150),
  ROOM        VARCHAR2(50),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP,
  IS_DELETED  NUMBER(1) DEFAULT 0 NOT NULL
);
